---
- name: Install required packages
  loop:
    - dnsmasq
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - dnsmasq

- name: Write server config
  notify:
    - Restart dnsmasq
  ansible.builtin.template:
    src: config.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - dnsmasq

- name: Start dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - dnsmasq

...
